### ISSUE TITLE
Could you help me with MQTT/WIll Topics/TLS?

### ISSUE THREAD

**Issue by KrYpToDeN** [jeroenst/espMQTT#5]
Hello.

Could you tell, please, how did you solve this problem with MQTT Will Topic and TLS.

This is your comment:
https://github.com/marvinroger/async-mqtt-client/issues/107#issuecomment-548812452

Our problem is almost the same. Our post - https://github.com/eclipse/mosquitto/issues/1715

Will topic works sometimes, not always.

Thank you.

**Comment by jeroenst** [comment]
It's a long time ago when I fixed this bug. I'm still using several esp8266 devices with ssl and will enabled. For what I remember I saw incomplete messages in the log of mosquitto. After some digging I found out that this was caused by the client.add function which created multiple network packets. When using the will topic some packets where not received anymore (except when using just one letter for username, password and will topic) causing incomplete mqtt packets. I also used Wireshark to observe this behavior. Now the mqtt packet is stored in less (or maybe just 1) network packets causing less overhead (due to headers) which makes will useable. But maybe when using long username, password or will topic it still fails, I don't know this.
